### ISSUE TITLE
redis test flakeyness

### ISSUE THREAD

**Issue by wez** [KumoCorp/kumomta#297]
get to the bottom of this:

```
thread 'throttle::test::redis_script_throttle_1_000' panicked at crates/throttle/src/throttle.rs:316:9:
throttled after 1160 iterations for limit 1000. diff=160 is not within tolerance 20
```

I'll bump the tolerance for now so that we're able to produce builds in the mean time

**Comment by djc** [comment]
Just wondering, have you observed this locally, or only in CI so far?

**Comment by wez** [comment]
only CI so far. I'm leaning towards this being a bit of a noisy neighbor issue, but I did spot a flakey run yesterday where the variance was over 20% and that feels a little too high from a statistical significance perspective.

**Comment by wez** [comment]
or this one with huge variance:

```
thread 'throttle::test::redis_script_throttle_1_000' panicked at crates/throttle/src/throttle.rs:316:9:
throttled after 1745 iterations for limit 1000. diff=745 is not within tolerance 200
```

**Comment by djc** [comment]
Oops, sorry about that!

**Comment by wez** [comment]
No worries; was really easy to overlook; neither of us detected it during review, and it didn't surface immediately in the tests!
